import { DurableObject } from "cloudflare:workers";
import { ATClient } from "./at.js";

const enc=new TextEncoder(),dec=new TextDecoder();
const b64=x=>{let s="";for(const b of new Uint8Array(x))s+=String.fromCharCode(b);return btoa(s).replaceAll("+","-").replaceAll("/","_").replaceAll("=","")};
const ub64=x=>{const s=x.replaceAll("-","+").replaceAll("_","/")+"===".slice((x.length+3)%4),z=atob(s);return Uint8Array.from(z,c=>c.charCodeAt(0))};
const rnd=n=>{const x=new Uint8Array(n);crypto.getRandomValues(x);return x};
const esc=x=>String(x??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const sha=x=>crypto.subtle.digest("SHA-256",enc.encode(x));
async function derive(password,salt){const base=await crypto.subtle.importKey("raw",enc.encode(password),"PBKDF2",false,["deriveBits"]);return crypto.subtle.deriveBits({name:"PBKDF2",salt,iterations:120000,hash:"SHA-256"},base,256)}
async function pwhash(password,salt){return b64(await derive(password,salt))}
async function encrypt(key,text){const iv=rnd(12),k=await crypto.subtle.importKey("raw",key,"AES-GCM",false,["encrypt"]);return b64(iv)+"."+b64(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,enc.encode(text)))}
async function decrypt(key,value){const [i,c]=value.split("."),k=await crypto.subtle.importKey("raw",key,"AES-GCM",false,["decrypt"]);return dec.decode(await crypto.subtle.decrypt({name:"AES-GCM",iv:ub64(i)},k,ub64(c)))}
function equal(a,b){const x=enc.encode(a),y=enc.encode(b);return x.length===y.length&&crypto.subtle.timingSafeEqual(x,y)}
function cookie(request,name){const x=(request.headers.get("Cookie")||"").split(/;\\s*/).find(v=>v.startsWith(name+"="));return x?decodeURIComponent(x.slice(name.length+1)):null}
function sessionCookie(token){return`aa_session=${encodeURIComponent(token)}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=604800`}
function html(title,body){return`<!doctype html><html><head><meta charset=utf-8><meta name=viewport content="width=device-width,initial-scale=1"><title>${esc(title)} · Laberflash</title><style>:root{color-scheme:dark}body{font:15px system-ui;max-width:1050px;margin:auto;padding:22px;background:#111;color:#eee}section{background:#1b1b1b;border:1px solid #333;border-radius:10px;padding:18px;margin:14px 0}input,button{font:inherit;padding:9px;border:1px solid #555;border-radius:6px;background:#101010;color:#eee}input{width:min(100%,400px)}button{cursor:pointer}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #333}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.ok{color:#75d99a}.err{color:#ff8d8d}.muted{color:#999}.inline{display:inline}</style></head><body>${body}</body></html>`}
function red(path){return new Response(null,{status:303,headers:{Location:path}})}
function out(body,status=200,headers={}){return new Response(body,{status,headers:{"Content-Type":"text/html; charset=utf-8","Cache-Control":"no-store",...headers}})}
function offers(data){const m=[];for(const o of data.subscribedOffers||[])for(const p of o.pack||[])if(String(p?.type||"").toLowerCase()==="data")m.push([o,p]);if(!m.length)throw Error("No data pack found");return m.find(x=>String(x[0].offerName||"").toLowerCase().includes("unlimited"))||m[0]}
function offerId(o){for(const k of ["offerId","id","offerID"])if(o?.[k])return String(o[k]);throw Error("Selected offer has no offerId")}
function remaining(p){if(String(p.unit||"").toLowerCase()!=="kilobytes")throw Error("Unsupported data unit: "+p.unit);return Math.max(0,Number(p.allocated)-Number(p.used))/1024}

export class ATScheduler extends DurableObject {
  constructor(ctx,env){super(ctx,env);this.sql=ctx.storage.sql;this.sql.exec(`CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);CREATE TABLE IF NOT EXISTS accounts(id TEXT PRIMARY KEY,username TEXT NOT NULL,password_cipher TEXT NOT NULL,contract_id TEXT,offer_id TEXT,enabled INTEGER NOT NULL DEFAULT 1,next_run_at INTEGER,last_remaining_mb REAL,last_status TEXT,last_message TEXT,updated_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS sessions(token_hash TEXT PRIMARY KEY,expires_at INTEGER NOT NULL);CREATE TABLE IF NOT EXISTS runs(id INTEGER PRIMARY KEY AUTOINCREMENT,account_id TEXT,started_at INTEGER NOT NULL,finished_at INTEGER,status TEXT,message TEXT,remaining_mb REAL);CREATE INDEX IF NOT EXISTS idx_accounts_next ON accounts(enabled,next_run_at);CREATE INDEX IF NOT EXISTS idx_runs_time ON runs(started_at DESC);`)}
  meta(k){return Array.from(this.sql.exec("SELECT value FROM meta WHERE key=?",k))[0]?.value}
  set(k,v){this.sql.exec("INSERT INTO meta(key,value) VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value",k,String(v))}
  setup(){return !!this.meta("admin_hash")}
  settings(){return{interval:Number(this.meta("interval")||3600),minMb:Number(this.meta("min_mb")||500),amountKb:this.meta("amount_kb")||"1048576",thresholdKb:this.meta("threshold_kb")||"1048576",resourceId:this.meta("resource_id")||"172",running:this.meta("running")==="1"}}
  async master(){let k=this.meta("master_key");if(!k){k=b64(rnd(32));this.set("master_key",k)}return ub64(k)}
  async verify(password){return this.setup()&&equal(await pwhash(password,ub64(this.meta("admin_salt"))),this.meta("admin_hash"))}
  async session(){const token=b64(rnd(32));this.sql.exec("INSERT INTO sessions(token_hash,expires_at) VALUES(?,?)",b64(await sha(token)),Date.now()+604800000);return token}
  async valid(request){const token=cookie(request,"aa_session");if(!token)return false;const h=b64(await sha(token)),row=Array.from(this.sql.exec("SELECT expires_at FROM sessions WHERE token_hash=?",h))[0];if(!row||Number(row.expires_at)<Date.now()){if(row)this.sql.exec("DELETE FROM sessions WHERE token_hash=?",h);return false}return true}
  async initialize(password){if(this.setup())throw Error("Already initialized");if(password.length<12)throw Error("Admin password must be at least 12 characters");const salt=rnd(16);this.set("admin_salt",b64(salt));this.set("admin_hash",await pwhash(password,salt));await this.master();this.set("interval",3600);this.set("min_mb",500);this.set("amount_kb","1048576");this.set("threshold_kb","1048576");this.set("resource_id","172");this.set("running","0")}
  async schedule(){if(!this.settings().running)return this.ctx.storage.deleteAlarm();const row=Array.from(this.sql.exec("SELECT MIN(next_run_at) next FROM accounts WHERE enabled=1 AND next_run_at IS NOT NULL"))[0];return row?.next?this.ctx.storage.setAlarm(Math.max(Date.now()+1000,Number(row.next))):this.ctx.storage.deleteAlarm()}
  async start(){this.set("running","1");this.sql.exec("UPDATE accounts SET next_run_at=? WHERE enabled=1 AND (next_run_at IS NULL OR next_run_at<?)",Date.now(),Date.now());await this.schedule();this.ctx.waitUntil(this.runDue(true));return red("/")}
  async stop(){this.set("running","0");await this.ctx.storage.deleteAlarm();return red("/")}
  async settingsPost(request){const f=await request.formData(),interval=Number(f.get("interval")),min=Number(f.get("min_mb"));if(!Number.isFinite(interval)||interval<30||!Number.isFinite(min)||min<0)throw Error("Invalid interval/minimum");this.set("interval",Math.floor(interval));this.set("min_mb",min);this.set("amount_kb",String(f.get("amount_kb")||"1048576"));this.set("threshold_kb",String(f.get("threshold_kb")||"1048576"));this.set("resource_id",String(f.get("resource_id")||"172"));if(this.settings().running)await this.schedule();return red("/")}
  async addAccount(request){const f=await request.formData(),username=String(f.get("username")||"").trim(),password=String(f.get("password")||"");if(!username||!password)throw Error("Username and password are required");const id=crypto.randomUUID();this.sql.exec("INSERT INTO accounts(id,username,password_cipher,enabled,next_run_at,updated_at) VALUES(?,?,?,?,?,?)",id,username,await encrypt(await this.master(),password),1,Date.now(),Date.now());if(this.settings().running)await this.schedule();return red("/")}
  async accountAction(id,action){if(action==="delete"){this.sql.exec("DELETE FROM accounts WHERE id=?",id);this.sql.exec("DELETE FROM runs WHERE account_id=?",id)}else this.sql.exec("UPDATE accounts SET enabled=CASE enabled WHEN 1 THEN 0 ELSE 1 END,updated_at=? WHERE id=?",Date.now(),id);if(this.settings().running)await this.schedule();return red("/")}
  async runDue(force=false){if(!this.settings().running&&!force)return;const s=this.settings(),now=Date.now(),accounts=Array.from(this.sql.exec("SELECT * FROM accounts WHERE enabled=1 AND (?=1 OR next_run_at IS NULL OR next_run_at<=?) ORDER BY next_run_at",force?1:0,now));for(const a of accounts){const started=Date.now();let left=null,status="ok",message="";try{const client=new ATClient(a.username,await decrypt(await this.master(),a.password_cipher));await client.login();let contract=a.contract_id,offersData;if(contract){try{offersData=await client.offers(contract)}catch(e){if(e.status!==400&&e.status!==404)throw e;contract=null}}if(!contract){const nav=await client.navigation();contract=String((nav.userDetails?.subscriptions||[]).find(x=>x.contractId)?.contractId||"");if(!contract)throw Error("navigation-list returned no contractId");offersData=await client.offers(contract)}const [offer,pack]=offers(offersData),currentOffer=offerId(offer);left=remaining(pack);if(!Number.isFinite(left))throw Error("Invalid allocated/used values");if(left<s.minMb){const result=await client.updateUnlimited({offerId:currentOffer,subscriptionId:contract,updateOfferResourceID:String(s.resourceId),amount:String(s.amountKb),refillThresholdValue:String(s.thresholdKb)});if(String(result.status)!=="200"||!result.isUpdated)throw Error("updateUnlimited failed: "+JSON.stringify(result).slice(0,500));message=left.toFixed(0)+" MB -> updateUnlimited successful"}else message=left.toFixed(0)+" MB; threshold "+s.minMb+" MB";this.sql.exec("UPDATE accounts SET contract_id=?,offer_id=?,last_remaining_mb=?,last_status=?,last_message=?,updated_at=?,next_run_at=? WHERE id=?",contract,currentOffer,left,"ok",message,Date.now(),Date.now()+s.interval*1000,a.id)}catch(e){status="error";message=String(e.message||e);this.sql.exec("UPDATE accounts SET last_status=?,last_message=?,updated_at=?,next_run_at=? WHERE id=?",status,message.slice(0,1000),Date.now(),this.settings().running?Date.now()+s.interval*1000:null,a.id);console.error("Laberflash "+a.username,e)}this.sql.exec("INSERT INTO runs(account_id,started_at,finished_at,status,message,remaining_mb) VALUES(?,?,?,?,?,?)",a.id,started,Date.now(),status,message.slice(0,1000),left)}await this.schedule()}
  async dashboard(){const s=this.settings(),accounts=Array.from(this.sql.exec("SELECT * FROM accounts ORDER BY username")),runs=Array.from(this.sql.exec("SELECT r.*,a.username FROM runs r LEFT JOIN accounts a ON a.id=r.account_id ORDER BY r.started_at DESC LIMIT 20"));const rows=accounts.map(a=>`<tr><td>${esc(a.username)}</td><td>${a.enabled?"<span class=ok>enabled</span>":"disabled"}</td><td>${a.last_remaining_mb==null?"—":Number(a.last_remaining_mb).toFixed(0)+" MB"}</td><td>${esc(a.last_status||"—")}</td><td><form class=inline method=post action="/accounts/${a.id}/toggle"><button>${a.enabled?"Disable":"Enable"}</button></form> <form class=inline method=post action="/accounts/${a.id}/delete" onsubmit="return confirm('Delete account?')"><button>Delete</button></form></td></tr>`).join(""),log= runs.map(r=>`<tr><td>${new Date(r.started_at).toLocaleString()}</td><td>${esc(r.username||"")}</td><td>${esc(r.status)}</td><td>${r.remaining_mb==null?"—":Number(r.remaining_mb).toFixed(0)+" MB"}</td><td>${esc(r.message||"")}</td></tr>`).join("");return out(html("Dashboard",`<h1>Laberflash Worker</h1><section><h2>Scheduler</h2><p>Status: ${s.running?"<span class=ok>Running</span>":"Stopped"} · Interval: ${s.interval}s · Minimum: ${s.minMb} MB</p><form class=inline method=post action=/start><button>Start</button></form> <form class=inline method=post action=/stop><button>Stop</button></form> <form class=inline method=post action=/run><button>Run now</button></form> <form class=inline method=post action=/logout><button>Logout</button></form></section><section><h2>Settings</h2><form method=post action=/settings><div class=grid><label>Interval seconds<br><input type=number min=30 name=interval value="${s.interval}" required></label><label>Minimum MB<br><input type=number min=0 name=min_mb value="${s.minMb}" required></label><label>Amount KB<br><input name=amount_kb value="${esc(s.amountKb)}" required></label><label>Refill threshold KB<br><input name=threshold_kb value="${esc(s.thresholdKb)}" required></label><label>updateOfferResourceID<br><input name=resource_id value="${esc(s.resourceId)}" required></label></div><br><button>Save settings</button></form></section><section><h2>AT accounts</h2><form method=post action=/accounts><div class=grid><label>Username / MSISDN<br><input name=username autocomplete=username required></label><label>Password<br><input type=password name=password autocomplete=new-password required></label></div><br><button>Add account</button></form><br><table><tr><th>Account</th><th>State</th><th>Remaining</th><th>Last status</th><th>Actions</th></tr>${rows||"<tr><td colspan=5 class=muted>No accounts.</td></tr>"}</table></section><section><h2>Recent runs</h2><table><tr><th>Time</th><th>Account</th><th>Status</th><th>Remaining</th><th>Message</th></tr>${log||"<tr><td colspan=5 class=muted>No runs.</td></tr>"}</table></section>`))}
  async handle(request){const u=new URL(request.url),p=u.pathname,m=request.method;if(!this.setup()){if(p==="/setup"&&m==="POST"){const f=await request.formData(),pw=String(f.get("password")||""),cf=String(f.get("confirm")||"");try{if(pw!==cf)throw Error("Passwords do not match");await this.initialize(pw);const t=await this.session();return new Response(null,{status:303,headers:{Location:"/","Set-Cookie":sessionCookie(t)}})}catch(e){return out(html("Setup error",`<h1>Setup error</h1><p class=err>${esc(e.message)}</p><a href="/">Try again</a>`),400)}}return out(html("Setup",`<h1>Laberflash Worker</h1><section><h2>First setup</h2><form method=post action=/setup><input type=password name=password minlength=12 placeholder="Admin password" required><br><br><input type=password name=confirm minlength=12 placeholder="Repeat password" required><br><br><button>Initialize</button></form><p class=muted>AT passwords are encrypted in private Durable Object storage.</p></section>`))}if(p==="/login"){if(m==="POST"){const f=await request.formData();if(!(await this.verify(String(f.get("password")||""))))return out(html("Login failed",`<h1>Login failed</h1><p class=err>Invalid password.</p><a href="/login">Try again</a>`),401);const t=await this.session();return new Response(null,{status:303,headers:{Location:"/","Set-Cookie":sessionCookie(t)}})}if(await this.valid(request))return red("/");return out(html("Login",`<h1>Laberflash Worker</h1><section><form method=post><input type=password name=password placeholder="Admin password" required autofocus><br><br><button>Login</button></form></section>`))}if(p==="/logout"&&m==="POST"){const t=cookie(request,"aa_session");if(t)this.sql.exec("DELETE FROM sessions WHERE token_hash=?",b64(await sha(t)));return new Response(null,{status:303,headers:{Location:"/login","Set-Cookie":"aa_session=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0"}})}if(!(await this.valid(request)))return red("/login");try{if(p==="/"&&m==="GET")return this.dashboard();if(p==="/settings"&&m==="POST")return this.settingsPost(request);if(p==="/accounts"&&m==="POST")return this.addAccount(request);const x=p.match(/^\/accounts\/([^/]+)\/(delete|toggle)$/);if(x&&m==="POST")return this.accountAction(x[1],x[2]);if(p==="/start"&&m==="POST")return this.start();if(p==="/stop"&&m==="POST")return this.stop();if(p==="/run"&&m==="POST"){this.ctx.waitUntil(this.runDue(true));return red("/")}return out("Not found",404)}catch(e){return out(html("Error",`<h1>Error</h1><section><p class=err>${esc(e.message||e)}</p><a href="/">Back</a></section>`),500)}}
  async alarm(){try{await this.runDue(false)}catch(e){console.error("Laberflash scheduler alarm failed",e);if(this.settings().running)await this.schedule()}}
  async fetch(request){return this.handle(request)}
}
